// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYpXj7CSIsfHRvtmjOScsC46aPnbgzj-8',
    appId: '1:428167432949:web:9773421f855c38338fd3bc',
    messagingSenderId: '428167432949',
    projectId: 'meter-splitter-app',
    authDomain: 'meter-splitter-app.firebaseapp.com',
    storageBucket: 'meter-splitter-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIDfidFeSr0Z8Ph0Qft436nyihBFD4K-c',
    appId: '1:428167432949:android:bbba51bd61e06f1e8fd3bc',
    messagingSenderId: '428167432949',
    projectId: 'meter-splitter-app',
    storageBucket: 'meter-splitter-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJ9vNaqmvUWIxod1vgr4rYfFHYOsPPbsI',
    appId: '1:428167432949:ios:7bc3ca56975446818fd3bc',
    messagingSenderId: '428167432949',
    projectId: 'meter-splitter-app',
    storageBucket: 'meter-splitter-app.firebasestorage.app',
    iosBundleId: 'com.example.meterSplitter',
  );

}